language: node_js

node_js:
  - 8.1.3

install:
  - npm install -g codecov

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g
  - npm install

script:
  - npm install
  - npm run test
  - codecov
  - npm run build

after_success:
  - firebase deploy --only hosting --token $TOKEN --project $PROJECT_ID

notifications:
  email:
    on_failure: change
    on_success: change

