language: node_js

node_js:
  - 8.1.3

install:
  - npm install -g codecov

branches:
  only:
    - master

before_script:
  - npm install -g

script:
  - npm install
  - npm run test
  - codecov

after_success:
  - chmod +x ./deploy.sh; ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change

