language: node_js

node_js:
  - 8.1.3

install:
  - npm install -g codecov

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g

script:
  - npm install
  - npm run test
  - codecov

after_success:
  - echo 'Triggering deployment...'
  - curl -s 'https://forge.laravel.com/servers/95687/sites/413691/deploy/http?token=$DEPLOY_TOKEN'
  - echo 'Deployment triggered!'

notifications:
  email:
    on_failure: change
    on_success: change

