language: node_js
node_js:
  - 8.1.3
install:
  - npm install -g codecov
script:
  - rm -rf node_modules
  - npm install
  - npm run test
  - codecov
  - npm run build
  - deploy
deploy:
  provider: firebase
  token:
    secure: $TOKEN
  project: $PROJECT_ID
  message: "Deploying to firebase..."
